version: "3.8"

services:
  db:
    image: postgres:15
    container_name: natura-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: natura_db
    volumes:
      - natura-pro_pgdata:/var/lib/postgresql/data

volumes:
  natura-pro_pgdata:
